# _config.yaml
title: Finleap Connect Helm Charts
description: A chart repo for all Finleap Connect Helm Charts.
theme: minima
url: "https://finleap-connect.github.io/charts/"
repo_name: finleap-connect

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
